### ISSUE TITLE
This looks very interesting and fills a gap

### ISSUE THREAD

**Issue by najak3d** [MateuszJot/universal-ui#2]
This asset/project seems to fill a market need.   Procedural (flutter-like) creation of a UI, especially if you add "Fluent-style" notation, is a very popular method for UI creation (e.g. Flutter is on-the-rise).

UI Toolkit is starting to fill this need, but what is tragically missing, IMO, is the C# markup/fluent style of coding a UI.  UI Toolkit is bound to UXML.

First off a question -- the Asset Store says "uses Unity UI" - but should probably be more explicit, given the advent of UI Toolkit, and the timing of your release (Dec 2022).   At this point, I'm not for certain which UI system you are using here.   I'm assuming it's the legacy object-based UI, and NOT the UI Toolkit.

Second, a 5 minute promotional video with narration would be helpful, and a few tutorial videos.   Here on Github, you should open up Discussions option, so that a community can form.

This needs more skinning examples (different styles, and demo's showing how to restyle).

If you could create a real-time Preview Mode where you edit the code, and poof, as soon as it compiles again, it shows the results of your edits in the Preview Window.   This is crucial as well.

I REALLY WANT TO SEE THIS PROJECT SUCCEED.   It's filling a real and growing market need, if "done right".

**Comment by najak3d** [comment]
Here's a link to Avalonia project called "Declarative.Markup" is their means of specifying the entire UI in C# code, via extensions and Fluent-pattern/Builder, which is very sleek and desirable.  

Example code looks like this:
```C#
public class MainView : ViewBase<MainViewModel>
{
    public static IValueConverter InverseBooleanConverter { get; } 
        = new FuncValueConverter<bool, bool>(b => !b);

    //This method is executed before View building
    protected override void OnCreated()
    {
        ViewModel = new MainViewModel();
    }

    //Define markup in Build method
    protected override object Build(MainViewModel vm) =>
        new Grid()
            
            .Styles(
                new Style<Button>(s => s.Class(":pointerover")) //make button red when pointer is over using avalonia styles
                    .Background(Brushes.Red)
            )

            .Cols("Auto, 100, *") // equivalent of Grid.ColumnDefintions property
            .Background(Brushes.Green) // the same as grid.Background = Brushes.Green
            .Children(
                
                new TextBlock()
                    .Text( @vm.TextVal ), // use @ character before to Bind control's property to ViewModel's property

                new TextBlock()
                    .Col(1) //equivalent of Grid.SetColumn(textBlock, 1)
                    .IsVisible( @vm.HideGreeting, //bind TextBlock.IsVisible to MainViewModel.HideGreeting property
                                bindingMode: BindingMode.OneWay, // we can set Binding mode if necessery
                                converter: InverseBooleanConverter ), //Set value converter to invert value
                    .Text( "Hello Avalonia" ), 

                new Button()
                    .Col(2) //equivalent of Grid.SetColumn(textBlock, 1)
                    // we don't actually need binding here, 
                    // so just direct set to Command on view model
                    .Command(vm.ClickButtonCommand) 
                    .Content("Click me") // Content = "Click me"
                    .Padding(8, 0, 0, 0) //Set left padding to 8
                    .With(ButtonStyle) //Execute LabelStyle method over TextBlock control 
            );

    private void ButtonStyle(Button b) => b
        .VerticalAlignment(VerticalAlignment.Center)
        .FontSize(12);
}
'''

**Comment by najak3d** [comment]
And MVU-style approach with Avalonia looks like this:

```C#
public class Component : ComponentBase
{
//markup part
    protected override object Build() =>
        new StackPanel()
            .Children(
                new TextBlock()
                    .Ref(out _textBlock1)
                    .Text("Hello world"),
                new TextBlock()
                    .Text(Bind(CounterText)),
                new Button()
                    .Content("Click me")
                    .OnClick(OnButtonClick)
            );
            
//code part
    [Inject] SampleDataService DataService { get; set; } = null!; //service injection

    public int Counter { get; set; }
    public string CounterText => $"Counter: {Counter}";  //no need to implement AvaloniaProperty or OnPropertyChanged behaviors, since component has registry of all properties and emits ProperyChanged event after changing state of component.

    private void OnButtonClick(RoutedEventArgs e)
    {
        Counter++;
        _textBlock1.Text = DataService.GetData();
        StateHasChanged(); //for now we have to call this method manually. In future there will be some additional triggers like user input, that will rise this method automatically
    }
}

**Comment by MateuszJot** [comment]
Hi, thanks for kind words. You're right - it uses the legacy UI system and actually I should have mentioned that. Also thank you for your interesting suggestions. Currently I'm working on optimization stuff and then I will think about the direction of where should this project go. Your suggestions will certainly be taken into account :)

**Comment by MateuszJot** [comment]
Discussions are now enabled :) 
https://github.com/MateuszJot/universal-ui/discussions
